baseurl = "https://sheenacook.github.io"
title = "Sheena Cook"
theme = "hugo-theme-cleanwhite-rsy"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
unsafe = true

[params]
    header_image = "https://cdn.pixabay.com/photo/2018/01/30/22/50/forest-3119826_1280.jpg"
    title = "Musings, mud and minor melancholy"
    SEOTitle = "Sheena Cook Poems"
    keyword = "Poems, Poetry, Blog, Gardening, Nature, Musings"


# Sidebar settings
    sidebar_about_description_line1 ="Poems inspired by time spent on my allotment."
    sidebar_about_description_line2 ="And the broader horizons of humour. Shuttling around in life's loom."
    sidebar_about_description_line3 ="The natural world is worth noticing."
    sidebar_avatar = "https://live.staticflickr.com/7473/15505448029_87d189ae8c_n.jpg"
    about_me = true

    featured_tags = false
    featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

    image_404 = ""
    title_404 = "We couldn't find what you were looking for..."

    omit_categories = false

    [[params.addtional_menus]]
#    title =  "ABOUT"
#    href =  "/top/about/"

    [params.social]
#    rss            = true
    email          = "me@sheenacook.com"

    [params.bookmarks]